name: elearning_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3

  # Database Offline
  sqflite:
    ^2.4.2

    # Backend
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3

  # File handling
  file_picker: ^10.3.3
  csv: ^6.0.0

  # Notifications
  flutter_local_notifications: ^19.5.0

  # UI
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1

  # Other utilities
  intl: ^0.20.2 # Date formatting
  shared_preferences: ^2.5.3 # Caching

  cupertino_icons: ^1.0.8

dev_dependencies:
  custom_lint:
  riverpod_lint: ^3.0.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
